// nobita-feedback-app-online/services/emailService.js

// SendGrid SDK ka istemaal. Ensure karein ki aapne 'npm install @sendgrid/mail' kiya ho.
const sgMail = require('@sendgrid/mail');

// Environment variable se API key set karein.
// Yeh Render/local .env se SENDGRID_API_KEY uthayega.
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

// Yeh woh email hai jo aapne .env mein set kiya hai (nobibot.host@gmail.com)
const SENDER_EMAIL = process.env.SENDER_EMAIL;

/**
 * Purane Nodemailer options ko SendGrid ke format mein convert karta hai.
 * @param {object} options - Email options like to, subject, htmlContent, textContent.
 * @returns {object} - SendGrid ke liye ready mail options object.
 */
const NOBITA_EMAIL_TEMPLATE = ({
    to, 
    subject, 
    htmlContent, 
    textContent 
}) => {
    // Critical validation
    if (!SENDER_EMAIL || !process.env.SENDGRID_API_KEY) {
        console.error("ERROR: SendGrid credentials are not fully set. Check SENDER_EMAIL and SENDGRID_API_KEY.");
        throw new Error("Email service is not configured correctly.");
    }

    // FIX: HTML Content Validation and Fallback
    // Agar htmlContent controller se nahi aata hai, toh textContent ko basic HTML mein wrap karein.
    let finalHtmlContent = htmlContent;
    if (!finalHtmlContent || typeof finalHtmlContent !== 'string' || finalHtmlContent.trim() === '') {
        // Line breaks ko <br> mein badalna for basic formatting
        const fallbackText = textContent || subject || "No content provided.";
        const htmlFallback = `<p>${fallbackText.replace(/\n/g, '<br>')}</p>`;
        finalHtmlContent = htmlFallback;
        console.log("WARN: HTML Content was missing or invalid, using text/subject as HTML fallback.");
    }
    
    return {
        to: to,
        // From address jo SendGrid se verified ho.
        from: SENDER_EMAIL, 
        subject: subject,
        // Text content optional hai, par best practice ke liye rakha hai.
        text: textContent, 
        // FIX: Guaranteed non-empty string for HTML.
        html: finalHtmlContent, 
        // ReplyTo set karne se user ka reply seedhe aapke Gmail par jaayega.
        replyTo: SENDER_EMAIL, 
    };
};


/**
 * SendGrid ke through email bhejta hai.
 * @param {object} mailOptions - Mail options object generated by NOBITA_EMAIL_TEMPLATE.
 * @returns {Promise<boolean>} - Agar email successfull hua to true, warna false.
 */
const sendEmail = async (mailOptions) => {
    // API key aur sender address available honi chahiye
    if (!mailOptions.from || !sgMail.client.apiKey) {
        console.error("Critical SendGrid configuration missing before send attempt.");
        return false;
    }
    
    try {
        // [response] ko destructure karke response object lein
        const [response] = await sgMail.send(mailOptions);
        
        console.log(`Email successfully sent to ${mailOptions.to} using SendGrid.`);
        console.log(`SendGrid API Status: ${response.statusCode}`);
        
        // 202 Accepted ka matlab hai ki SendGrid ne email successfully le liya hai.
        return response.statusCode === 202; 
    } catch (error) {
        // Detailed error log
        const errorDetails = error.response 
            ? JSON.stringify(error.response.body, null, 2) 
            : error.message;
        console.error("SendGrid Email Delivery Error:", errorDetails);
        
        return false;
    }
};

module.exports = { sendEmail, NOBITA_EMAIL_TEMPLATE };
